# This is a basic workflow to help you get started with Actions

name: rules

on:
  push:
    branches:
      - master
  schedule:
    - cron: '50 6,20 * * *'

  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      
      - name: Print current directory
        run: |
          pwd

      - name: Run a one-line script
        run: python Action/rules.py

      - name: Commit files
        run: |
          git config --local user.email "zy0462@gmail.com"
          git config --local user.name "zyl0462"
          git add ./*
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
